{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ (index .Values.ingress.hosts 0).host }}
    http:
      paths:
      - path: {{ (index (index .Values.ingress.hosts 0).paths 0).path }}
        pathType: {{ (index (index .Values.ingress.hosts 0).paths 0).pathType }}
        backend:
          service:
            name: fastapi-gateway
            port: { number: 80 }
{{- end }}
